### ISSUE TITLE
Clickable compile error locations gone?

### ISSUE THREAD

**Issue by spinicist** [vector-of-bool/vscode-cmake-tools#94]
Hi,

I'm not sure if this is a problem with VS Code itself, or the CMake Tools extension, or something else. Thought I'd ask here first to start tracking the problem down.

When I used to compile, when I got an error, the location of the error came up underlined in the output, and I could Cmd+Click it to go directly to the error location. At some point in the last few weeks or so, an update of something has removed that functionality. Does anyone have an idea how I can get it back?

Sorry to be vague about when this happened - I was working on some Python code for a few weeks and it's only now that I've swapped back to C++ after several updates that I've noticed this.

**Comment by vector-of-bool** [comment]
I definitely didn't _remove_ the feature, so it's certainly a bug. Could I see some example compiler output that isn't being parsed? I can use the output in a test case to get this issue fixed and prevent future regression.

**Comment by harrishancock** [comment]
I noticed that `enableOutputParsers` is spelled `enabledOutputParsers` in package.json (note `enable` versus `enabled`), introduced in ba72b1b4500f09cfbb1b2ab407b261dd76b528b2. Perhaps that is the cause?

At any rate, here's some output that does not get clickable links for me: https://gist.github.com/harrishancock/307741231c24e16e6f8d86d92a14883e

**Comment by spinicist** [comment]
Sorry for the delay in responding, here's a short example with a deliberate error introduced:
`
[vscode] Executing command: cmake --build /Users/Tobias/Code/QUIT/build --target qidespot1 --config RelWithDebInfo -- -j 6
[  3%] Generating version_depend_dummy
[ 21%] Built target qimdl
-- Found Git: /usr/bin/git (found version "2.5.4 (Apple Git-61)") 
[ 46%] Built target qisig
[ 67%] Built target qiseq
-- Version: 1.1-215-g578d742-dirty
[ 67%] Built target qi_version
[ 92%] Built target qi
Scanning dependencies of target qidespot1
[ 96%] Building CXX object CMakeFiles/qidespot1.dir/Source/qidespot1.cpp.o
/Users/Tobias/Code/QUIT/Source/qidespot1.cpp:303:49: error: expected ';' after expression
        cout << "Writing results files." << endl
                                                ^
                                                ;
1 error generated.
make[3]: *** [CMakeFiles/qidespot1.dir/Source/qidespot1.cpp.o] Error 1
make[2]: *** [CMakeFiles/qidespot1.dir/all] Error 2
make[1]: *** [CMakeFiles/qidespot1.dir/rule] Error 2
make: *** [qidespot1] Error 2
[vscode] cmake existed with status 2
`

**Comment by vector-of-bool** [comment]
Sorry to leave this open for so long. With the holidays, new year, and this "real life" thing getting in the way, I haven't had much time to work on this. I'm planning on getting right back on track as soon as possible. Expect these issues to get fixed in the next release.

**Comment by spinicist** [comment]
No problem - for similar reasons I haven't been coding much recently!

**Comment by vector-of-bool** [comment]
Hmm... It looks like I'm parsing the error fine. Are you seeing the errors missing with every compile error, or only certain ones?

I have a suspicion that the missing error here is because I'm pointing the diagnostic at the 48th column of that line, which is one past the end. Perhaps VSCode is not happy with diagnostics that are at the end of the line?

**Comment by spinicist** [comment]
I don't think that's the issue - I deliberately introduced a syntax error in the middle of the line and the same thing is happening. Maybe I have an option set wrong somewhere?

`[ 90%] Building CXX object CMakeFiles/qinewimage.dir/Source/qinewimage.cpp.o
/Users/Tobias/Code/QUIT/Source/qinewimage.cpp:75:15: error: member reference type 'QI::VolumeF::SpacingType' (aka 'Vector<SpacingValueType, 3U>') is not a pointer; maybe you meant to use '.'?
    imgSpacing->Fill(1.0);
    ~~~~~~~~~~^~
              .
1 error generated.`

**Comment by vector-of-bool** [comment]
Made some changes to the error parser. Not sure if it will fix this, but it might? Are you still seeing this problem in the latest version (0.9.4)?

**Comment by spinicist** [comment]
Sorry, no luck:
```[ 98%] Building CXX object CMakeFiles/qidespot2fm.dir/Source/qidespot2fm.cpp.o
/Users/Tobias/Code/QUIT/Source/qidespot2fm.cpp:90:28: error: cannot take the address of an rvalue of type 'bool'
        if (isfinite(T1) &!& (T1 > m_sequence->TR())) {
                           ^  ~~~~~~~~~~~~~~~~~~~~~
1 error generated.```
Am I supposed to have an option enabled somewhere? I forget.

**Comment by vector-of-bool** [comment]
It should "just work" for your case. What `cmake.*` settings do you have?

**Comment by spinicist** [comment]
This is the entirety of my user settings.json:
```
{
    "editor.fontFamily": "'Source Code Pro', Menlo, Monaco, 'Courier New', monospace",
    "editor.fontWeight": "400",
    "editor.fontSize": 16,
    "editor.renderWhitespace": "all",
    "editor.insertSpaces": true,
    "editor.minimap.enabled": true,
    "cmake.parallelJobs": 6,
    "git.confirmSync": false,
    "workbench.colorTheme": "Default Light+",
    "workbench.iconTheme": "vs-seti",
    "[cpp]": {
        "editor.quickSuggestions": false
    },
    "[c]": {
        "editor.quickSuggestions": false
    }
}
```
And then the projects settings.json:
```
{
    "search.exclude": {
        "build": true,
        "External": true
    }
,
"files.associations": {
    "*h*h*hxx*h*incstddef": "cpp",
    "exception": "cpp",
    "initializer_list": "cpp",
    "new": "cpp",
    "stdexcept": "cpp",
    "typeinfo": "cpp",
    "__config": "cpp",
    "__split_buffer": "cpp",
    "deque": "cpp",
    "hash_map": "cpp",
    "hash_set": "cpp",
    "iterator": "cpp",
    "queue": "cpp",
    "stack": "cpp",
    "utility": "cpp",
    "valarray": "cpp",
    "*.in": "cpp",
    "cstddef": "cpp",
    "__locale": "cpp",
    "limits": "cpp",
    "iostream": "cpp",
    "alignedvector3": "cpp",
    "fft": "cpp"
}
}
```
Some of this stuff has been inserted automatically by *something*, in particular the file associations I definitely didn't addd!

**Comment by spinicist** [comment]
PS - Anything to do with the fact I'm on a Mac???

**Comment by vector-of-bool** [comment]
It's been a while. Is this issue still presenting itself?

**Comment by spinicist** [comment]
I finally did what I should have done ages ago - I uninstalled all extensions, and re-installed them.

It appears to be an incompatibility with @donjayamanne's Python extension. If I have only C/C++ and the two CMake extensions installed, everything is fine. Installing the Python extension, and the clickable errors no longer appear.

**Comment by vector-of-bool** [comment]
Interesting observation. I've been using his Python extension since the very beginning and have never seen this issue. It's a good lead, though.

**Comment by nsubtil** [comment]
I've been having the exact same symptoms, and it turns out uninstalling the Python extension mentioned before fixed it as well for me. Thanks @spinicist for the detective work.

**Comment by meuter** [comment]
same here, removed the Python extension, and it works

**Comment by nsubtil** [comment]
I've recently seen the same issue crop up again, with slightly different symptoms. The Python extension is not installed this time.

It seems like the parser only detects errors where the full path to the source file is present. For some reason, many errors show up with relative paths, and those are not recognized.

I don't really recall if error messages always included the full file path before (i.e., this could be a recent toolchain change?), but it looks like the parser is having trouble with this right now.

**Comment by vector-of-bool** [comment]
I know it's been a while, but can anyone confirm this is still an issue in the latest version?

**Comment by spinicist** [comment]
Hi,

Yes, this still seems to be an issue. However - 
1. I have the Python extension installed and enabled at the moment
2. My `cmake` settings are:
```
    "cmake.parallelJobs": 3,
    "cmake.useCMakeServer": false, // Bug in CMake Server means configure/generatae run on every build
    "cmake.buildDirectory": "${workspaceRoot}/cmake_build",
```

I disabled the CMake Server a while ago due to a bug that I forget. I guess I should try re-enabling that? Any other things I can try to help you debug further?

**Comment by vector-of-bool** [comment]
Sorry to go quiet for so long. I got wrapped up in more recent release stuff. Did changing the CMake-Server setting fix anything? Other than that, I'm still a bit lost on this issue.

**Comment by spinicist** [comment]
Sorry for delay in responding.

I've set up a new laptop recently, so this has a fresh install of VSCode (Insiders) and fresh extensions. I still don't see clickable error locations in the Output tab. However, the errors do get listed in the Problems tab, and I can click on them there. Sometimes the Problems go a bit stale and I have to close and re-open the workspace, but mostly it works.

Hence I'm going to close this issue because it's not really an issue for me anymore.

I love the new CMake toolbar - but I'm not sure if that's coming from the CMake extension or CMake Tools!
